### PR TITLE
Create README and fix LICENSE

### PR DESCRIPTION
**Pull request by pdt1806**
@tobycm 

Make sure to read the comments (especially the TODOs) to see how the README will be when completed.

Try to apply for GitHub Sponsors again.

### CODE REVIEW

**Comment by tobycm** [comment]
> Try to apply for GitHub Sponsors again.

Me??!?

**Comment by tobycm** [comment]
Also LICENSE was intentional lmao

**Comment by pdt1806** [comment]
> > Try to apply for GitHub Sponsors again.
> 
> Me??!?

sí

**Review by tobycm — APPROVED** [review]
thank you bro

**Pull request merged**
